### ISSUE TITLE
Upgrade mapbox samples' map style

### ISSUE THREAD

**Issue by weichix** [DCgov/opendatadc-starterkit#9]
From Mapbox: 

![image](https://user-images.githubusercontent.com/25930018/80839972-5097c600-8bca-11ea-967d-4aec19033dd8.png)

**Comment by weichix** [comment]
[Migrating to the modern static tiles API](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/?mkt_tok=eyJpIjoiWlRsbU5tTXdPV1JqTkdVMyIsInQiOiJadHdSZk9pY1wvMkRFRmJBUUdJSnBmNWlBXC85UlpDZVRtbUNWTnpBY1dXcnRDYlZyUlB6NnJ6V0R4TkRxXC96TDcxT1RXV0FZYmQ1NzVjNisyWFVzbDJsTHo2TldVQ0pxRzhCQmI1WUExR3VsUG5zODhNVk9GQUdXU2Q3bzVCdDFYSiJ9)

**Comment by unlockedSound** [comment]
work to be done internally
